### ISSUE TITLE
Set up Staging/Production environments

### ISSUE THREAD

**Issue by krissy** [womenhackfornonprofits/earthlinks#3]
# What

Set up Staging and Production environments.

# Tasks
- [ ] Pick a host E.g. Heroku
- [ ] Set the project up to deploy to your host (e.g.  (e.g. https://devcenter.heroku.com/articles/getting-started-with-rails5)
- [ ] This may involve setting up a way to manage environment variables (e.g. https://github.com/bkeepers/dotenv)
- [ ] Document the deployment process from your local machine for everyone in the team. Perhaps the GitHub wiki? Or README? Ensure no private login details or secure keys are shared here.
